app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::auth();
Route::get('/home', 'HomeController@index');

Route::resource('/', 'Web\User\BerandaController');
Route::resource('/daftar', 'Web\User\DaftarController');
Route::resource('/cekdaftar', 'Web\User\CekDaftarController');
Route::resource('/kartudaftar', 'Web\User\KartuDaftarController');
Route::resource('/cekstatus', 'Web\User\CekStatusController@create');
Route::resource('/persyaratan', 'Web\User\PersyaratanController');
Route::get('/persyaratan/{id}/{ket}', 'Web\User\PersyaratanController@show');
Route::resource('/status', 'Web\User\CekStatusController');
Route::resource('/bayardaftar', 'Web\User\BayarDaftarController');
Route::resource('/kontak', 'Web\User\KontakController');
Route::get('/pdfkartudaftar/{id}', 'Web\User\DaftarController@kartudaftar');
Route::get('/pdfbayar/{id}', 'Web\User\DaftarController@bayar');
Route::get('/downloadkartu/{id}', 'Web\User\DaftarController@downloadkartu');

Route::auth();

//ADMIN
Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/siswa/create', 'Web\Admin\SiswaController@create');
Route::resource('/admin/siswa', 'Web\Admin\SiswaController');
Route::put('/admin/persyaratan/update/{id}/{tipe}', 'Web\Admin\PersyaratanController@update');
Route::resource('/admin/infolulus', 'Web\Admin\LulusController');
Route::put('/admin/infolulus/update/{id}', 'Web\Admin\LulusController@update');
Route::resource('/admin/pendaftaran', 'Web\Admin\PendaftaranController');
Route::put('/admin/infolulus/update/{id}', 'Web\Admin\LulusController@update');
Route::resource('/admin/history', 'Web\Admin\HistoryController');
Route::resource('/admin/kontak', 'Web\Admin\KontakController');
Route::resource('/admin/informasi', 'Web\Admin\InformasiController');
Route::resource('/admin/persyaratan', 'Web\Admin\PersyaratanController');
Route::resource('/admin/cetak/formulir', 'Web\Admin\CetakController');
Route::get('/admin/cetak/formulir/print/{id}', 'Web\Admin\CetakController@formulir');

Route::get('/admin/cetak/datasiswa', 'Web\Admin\CetakController@datasiswa');
Route::get('/admin/cetak/datasiswaexcel/{type}', 'Web\Admin\CetakController@datasiswaexcel');

Route::get('/admin/cetak/formulir-semua/print', 'Web\Admin\CetakController@formulirsemua');
Route::get('/admin/cetak/formulir-kosong/print', 'Web\Admin\CetakController@formulirkosong');
Route::resource('/admin/cetak/penerimaan', 'Web\Admin\CetakController@penerimaan');
Route::resource('/admin/cetak/pendaftaran', 'Web\Admin\CetakController@pendaftaran');
Route::resource('/admin/pengaturan', 'Web\Admin\PengaturanController');
Route::resource('/admin/jurusan', 'Web\Admin\JurusanController');

//KAJUR

Route::resource('/kajur/beranda', 'Web\Kajur\BerandaController');
Route::resource('/kajur/siswa', 'Web\Kajur\SiswaController');

//PPDB

Route::resource('/ppdb/beranda', 'Web\AdminPPDB\BerandaController');
Route::resource('/ppdb/siswa', 'Web\AdminPPDB\SiswaController');
Route::resource('/ppdb/persyaratan', 'Web\AdminPPDB\PersyaratanController');
Route::resource('/ppdb/cetak/formulir', 'Web\AdminPPDB\CetakController');
Route::get('/ppdb/cetak/formulir/print/{id}', 'Web\AdminPPDB\CetakController@formulir');
Route::get('/ppdb/cetak/formulir-semua/print', 'Web\AdminPPDB\CetakController@formulirsemua');
Route::get('/ppdb/cetak/formulir-kosong/print', 'Web\AdminPPDB\CetakController@formulirkosong');

Route::resource('/ppdb/cetak/penerimaan', 'Web\AdminPPDB\CetakController@penerimaan');

app/Http/Controllers/Web/Admin/SiswaController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\SiswaRequest;
use App\Http\Controllers\Controller;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;

use App\Siswa;
use App\Jurusan;
use App\Status;
use App\Pekerjaan;
use App\Agama;
use App\History;
use App\Meta;
use App\Tahun;
use Auth;

class SiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:superadmin');
    }

    public function index()
    {
        $no = 1;
        $tahun_aktif = Meta::where('id', 1)->get()->first();
        $siswa = Siswa::where('tahun_ajaran', $tahun_aktif->meta_value)->orderBy('id', 'DESC')->get()->all();

        return view('admin.siswa.siswa', compact('siswa', 'no'));
    }

    public function create()
    {
        $jurusan = Jurusan::where('jurusan', 'not like', "-")->lists('jurusan','jurusan');
        $agama = Agama::lists('agama', 'agama');
        $pekerjaan = Pekerjaan::lists('pekerjaan', 'pekerjaan');
        $status = Status::lists('status', 'status');

        $tadaf = Meta::where('id', 2)->lists('meta_value', 'meta_value');

        return view('admin.siswa.tambah_siswa', compact('jurusan', 'status', 'pekerjaan', 'agama', 'tadaf'));
    }

    public function store(SiswaRequest $request)
    {
        $tahun = Meta::where('id', 2)->get()->first();
        // SIMPAN DATA SISWA
        $siswa = $request->all();
        $siswa['status_bayar'] = 'Belum Lunas';
        $siswa['status_lulus'] = '-';
        $siswa['id_daftar'] = str_random(10);
        $siswa['tahun_ajaran'] = $tahun->meta_value;

        if ($request->hasFile('img_ijazah')) {
            $siswa['img_ijazah'] = $this->saveIjazah($request->file('img_ijazah'), 'ijazah', $request->nama);
        } else {
            $siswa['img_ijazah'] = '-';
        }

        if ($request->hasFile('img_skhu')) {
            $siswa['img_skhu'] = $this->saveSKHU($request->file('img_skhu'), 'skhu', $request->nama);
        } else {
            $siswa['img_skhu'] = '-';
        }

        Siswa::create($siswa);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Siswa Baru atas nama " . $siswa['nama'];
        History::create($histori);

        $notification = array(
            'message' => 'Siswa Baru "' . $siswa['nama'] . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.siswa.create')->with($notification);
    }

    public function show($id)
    {
        $siswa = Siswa::findOrFail($id);

        return view('admin.siswa.show_siswa', compact('siswa'));
    }

    public function edit($id)
    {
        $siswa = Siswa::findOrFail($id);

        $jurusan = Jurusan::lists('jurusan', 'jurusan');
        $agama = Agama::lists('agama', 'agama');
        $pekerjaan = Pekerjaan::lists('pekerjaan', 'pekerjaan');
        $status = Status::lists('status', 'status');
        $tadaf = Tahun::lists('tahun', 'tahun');

        return view('admin.siswa.edit_siswa', compact('siswa', 'jurusan', 'status', 'pekerjaan', 'agama', 'tadaf'));
    }

    public function update(SiswaRequest $request, $id)
    {
        $siswa = Siswa::findOrFail($id);

        $datasiswa = $request->only(
            'nama',
            'jk',
            'tempat_lahir',
            'tanggal_lahir',
            'nisn',
            'alamat',
            'kelas',
            'agama',
            'asal_sekolah',
            'nomor_sttb',
            'nomor_skhu',
            'nomor_peserta_ujian_smp',
            'ayah_nama',
            'ayah_pendidikan',
            'ayah_pekerjaan',
            'ibu_nama',
            'ibu_pendidikan',
            'ibu_pekerjaan',
            'alamat_orangtua',
            'telp',
            'jurusan_1',
            'jurusan_2',
            'status_bayar',
            'tahun_ajaran',
            'daftar',
            'ket','info'
        );

        if ($request->hasFile('img_ijazah')) {
            $this->deletePhoto($siswa->img_ijazah);
            $datasiswa['img_ijazah'] = $this->saveIjazah($request->file('img_ijazah'), 'ijazah', $request->nama);
        }

        if ($request->hasFile('img_skhu')) {
            $this->deletePhoto($siswa->img_skhu);
            $datasiswa['img_skhu'] = $this->saveSKHU($request->file('img_skhu'), 'skhu', $request->nama);
        }

        $siswa->update($datasiswa);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Siswa atas nama " . $datasiswa['nama'];
        History::create($histori);

        $notification = array(
            'message' => 'Data Siswa "' . $datasiswa['nama'] . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.siswa.index')->with($notification);
    }

    public function destroy($id)
    {
        $siswa = Siswa::findOrFail($id);

        $this->deletePhoto($siswa->img_ijazah);
        $this->deletePhoto($siswa->img_skhu);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Siswa atas nama " . $siswa->nama;
        History::create($histori);

        $notification = array(
            'message' => 'Data Siswa "' . $siswa->nama . '" berhasil dihapus.',
            'alert-type' => 'error'
        );

        Siswa::find($id)->delete();
        return redirect()->route('admin.siswa.index')->with($notification);
    }

    protected function saveIjazah(UploadedFile $photo, $ket, $nama)
    {
        $fileName = $nama . '-' . $ket . '-' . str_random(10) . '.' . $photo->guessClientExtension();
        $destinationPath = 'itlabil/image/image_user';
        $photo->move($destinationPath, $fileName);
        return $fileName;
    }

    protected function saveSKHU(UploadedFile $photo, $ket, $nama)
    {
        $fileName = $nama . '-' . $ket . '-' . str_random(10) . '.' . $photo->guessClientExtension();
        $destinationPath = 'itlabil/image/image_user';
        $photo->move($destinationPath, $fileName);
        return $fileName;
    }

    public function deletePhoto($filename)
    {
        $path = 'itlabil/image/image_user/' . $filename;
        return File::delete($path);
    }
}

app/Http/Controllers/Web/AdminPPDB/SiswaController.php
<?php

namespace App\Http\Controllers\Web\AdminPPDB;

use App\Agama;
use App\History;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\SiswaRequest;
use App\Jurusan;
use App\Meta;
use App\Pekerjaan;
use App\Siswa;
use App\Status;
use Illuminate\Support\Facades\Auth;

class SiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }

    public function index()
    {
        $no = 1;
        $tahun_aktif = Meta::where('id', 1)->get()->first();
        $siswa = Siswa::where('tahun_ajaran', $tahun_aktif->meta_value)->orderBy('id', 'DESC')->get()->all();

        return view('ppdb.siswa.siswa', compact('siswa', 'no'));
    }

    public function create()
    {
        $jurusan = Jurusan::where('jurusan', 'not like', "-")->lists('jurusan','jurusan');
        $agama = Agama::lists('agama', 'agama');
        $pekerjaan = Pekerjaan::lists('pekerjaan', 'pekerjaan');
        $status = Status::lists('status', 'status');

        $tadaf = Meta::where('id', 2)->lists('meta_value', 'meta_value');

        return view('ppdb.siswa.tambah_siswa', compact('jurusan', 'status', 'pekerjaan', 'agama', 'tadaf'));
    }

    public function store(SiswaRequest $request)
    {
        $tahun = Meta::where('id', 2)->get()->first();
        // SIMPAN DATA SISWA
        $siswa = $request->all();
        $siswa['status_bayar'] = 'Belum Lunas';
        $siswa['status_lulus'] = '-';
        $siswa['id_daftar'] = str_random(10);
        $siswa['tahun_ajaran'] = $tahun->meta_value;

        if ($request->hasFile('img_ijazah')) {
            $siswa['img_ijazah'] = $this->saveIjazah($request->file('img_ijazah'), 'ijazah', $request->nama);
        } else {
            $siswa['img_ijazah'] = '-';
        }

        if ($request->hasFile('img_skhu')) {
            $siswa['img_skhu'] = $this->saveSKHU($request->file('img_skhu'), 'skhu', $request->nama);
        } else {
            $siswa['img_skhu'] = '-';
        }

        Siswa::create($siswa);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Siswa Baru atas nama " . $siswa['nama'];
        History::create($histori);

        $notification = array(
            'message' => 'Siswa Baru "' . $siswa['nama'] . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('ppdb.siswa.create')->with($notification);
    }


    public function show($id)
    {
        $siswa = Siswa::findOrFail($id);

        return view('ppdb.siswa.show_siswa', compact('siswa'));
    }

    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Web/Kajur/SiswaController.php
<?php

namespace App\Http\Controllers\Web\Kajur;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Meta;
use App\Siswa;
use App\History;
use Auth;

class SiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:kajur');
    }

    public function index()
    {
        $no = 1;

        $tahun_aktif = Meta::where('id',1)->get()->first();

        $name = Auth::user()->name;

        if ($name=='Kajur TKJ') {
            $jurusan="Teknik Komputer dan Jaringan";
        } else if($name=='Kajur MM'){
            $jurusan="Multimedia";
        } else if($name=='Kajur FM'){
            $jurusan="Farmasi";
        } else if($name=='Kajur AP'){
            $jurusan="Administrasi Perkantoran";
        } else if($name=='Kajur AK'){
            $jurusan="Akuntansi";
        } else {
            $jurusan="Pemasaran";
        }
        
        $siswa = Siswa::where('tahun_ajaran',$tahun_aktif->meta_value)
                        ->where('jurusan_1',$jurusan)
                        ->orderBy('nama','ASC')->get()->all();

        return view('kajur.siswa.siswa', compact('siswa','no'));
    }

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $siswa = Siswa::findOrFail($id);

        if ($siswa->status_lulus=="Lulus") {
            if($siswa->jurusan_1==$siswa->jurusan_2){
                $datasiswa['status_lulus'] = "Tidak Lulus";
                $datasiswa['jurusan_2'] = '-';
                $datasiswa['ket'] = $siswa->ket.' - Tidak Lulus di Jurusan '.$siswa->jurusan_1;
            }else{
                if ($siswa->jurusan_2=='-') {
                    $datasiswa['status_lulus'] = "Tidak Lulus";
                } else {
                    $datasiswa['status_lulus'] = "-";
                    $datasiswa['jurusan_1'] = $siswa->jurusan_2;
                    $datasiswa['jurusan_2'] = '-';
                    $datasiswa['ket'] = $siswa->ket.' - Tidak Lulus di Jurusan '.$siswa->jurusan_1;
                }
            }
        } else {
            $datasiswa['status_lulus'] = "Lulus";
        }
        

        $siswa->update($datasiswa);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Status Penerimaan atas nama ".$siswa->nama." menjadi ".$datasiswa['status_lulus'];
        History::create($histori);

        $notification = array(
            'message' => 'Status Penerimaan Siswa "'.$siswa['nama'].'" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('kajur.siswa.index')->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/siswa/edit_siswa.blade.php
@extends('layouts.admin')

@section('content')

    <section class="content-header">
        <h1>
            Data Siswa
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                
                        {!! Form::model($siswa, ['route' => ['admin.siswa.update', $siswa],'method' =>'patch','class'=>'form-horizontal','files'=>true])!!}
                            @include('form.ubah._admin_siswa', ['model' => $siswa])
                        {!! Form::close() !!}
         
            </div>
        </div>
    </section>
@endsection

resources/views/admin/siswa/show_siswa.blade.php
@extends('layouts.admin')

@section('content')

<section class="content-header">
    <h1>
        Show Data Siswa - {{ $siswa->nama }}
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">

            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Data</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <table class="table table-striped">
                        <tr>
                            <td width="200px">ID Daftar</td>
                            <td>: {{$siswa->id_daftar}}</td>
                        </tr>
                        <tr>
                            <td width="200px">Jenis Kelamin</td>
                            <td>: {{$siswa->jk}}</td>
                        </tr>
                        <tr>
                            <td>Tempat Tanggal Lahir</td>
                            <td>: {{$siswa->tempat_lahir}}, {{$siswa->tanggal_lahir}}</td>
                        </tr>
                        <tr>
                            <td>Agama</td>
                            <td>: {{$siswa->agama}}</td>
                        </tr>
                        <tr>
                            <td>Alamat</td>
                            <td>: {{$siswa->alamat}}</td>
                        </tr>
                        <tr>
                            <td>Nomor Telp</td>
                            <td>: {{$siswa->telp}}</td>
                        </tr>
                        <tr>
                            <td>Kelas</td>
                            <td>: {{$siswa->kelas}}</td>
                        </tr>
                        <tr>
                            <td>NISN</td>
                            <td>: {{$siswa->nisn}}</td>
                        </tr>
                        <tr>
                            <td>Asal Sekolah</td>
                            <td>: {{$siswa->asal_sekolah}}</td>
                        </tr>
                        <tr>
                            <td>Nomor STTB/Ijazah</td>
                            <td>: {{$siswa->nomor_sttb}}</td>
                        </tr>
                        <tr>
                            <td>Nomor SKHU</td>
                            <td>: {{$siswa->nomor_skhu}}</td>
                        </tr>
                        <tr>
                            <td>Nomor Peserta Ujian SMP</td>
                            <td>: {{$siswa->nomor_peserta_ujian_smp}}</td>
                        </tr>
                        <tr>
                            <td colspan="2"><strong>Jurusan Yang dipilih</strong></td>
                        </tr>
                        <tr>
                            <td>Jurusan 1</td>
                            <td>: {{$siswa->jurusan_1}}</td>
                        </tr>
                        <tr>
                            <td>Jurusan 2</td>
                            <td>: {{$siswa->jurusan_2}}</td>
                        </tr>
                        <tr>
                            <td>Tahun Ajaran</td>
                            <td>: {{$siswa->tahun_ajaran}}</td>
                        </tr>
                        <tr>
                            <td colspan="2"><strong>Status Bayar Pendaftaran</strong></td>
                        </tr>
                        <tr>
                            <td>Administrasi</td>
                            @if($siswa->status_bayar=="Lunas")
                            <td>: <span class="badge bg-green">{{ $siswa->status_bayar }}</span></td>
                            @else
                            <td>: <span class="badge bg-red">{{ $siswa->status_bayar }}</span></td>
                            @endif
                        </tr>
                        <tr>
                            <td>Tipe Daftar</td>
                            @if($siswa->daftar=="Online")
                            <td>: <span class="badge bg-green">{{ $siswa->daftar }}</span></td>
                            @else
                            <td>: <span class="badge bg-red">{{ $siswa->daftar }}</span></td>
                            @endif
                        </tr>
                        <tr>
                            <td>Keterangan</td>
                            <td>: {{$siswa->ket}}</td>
                        </tr>
                        <tr>
                            <td>Info Siswa</td>
                            <td>: {{$siswa->info}}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title">Orang Tua</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <table class="table table-striped">
                        <tr>
                            <td width="200px">Nama Ayah</td>
                            <td>: {{$siswa->ayah_nama}}</td>
                        </tr>
                        <tr>
                            <td>Pekerjaan Ayah</td>
                            <td>: {{$siswa->ayah_pekerjaan}}</td>
                        </tr>
                        <tr>
                            <td>Pendidikan Ayah</td>
                            <td>: {{$siswa->ayah_pendidikan}}</td>
                        </tr>
                        <tr>
                            <td>Nama Ibu</td>
                            <td>: {{$siswa->ibu_nama}}</td>
                        </tr>
                        <tr>
                            <td>Pekerjaan Ibu</td>
                            <td>: {{$siswa->ibu_pekerjaan}}</td>
                        </tr>
                        <tr>
                            <td>Pendidikan Ibu</td>
                            <td>: {{$siswa->ibu_pendidikan}}</td>
                        </tr>
                        <tr>
                            <td>Alamat Orangtua</td>
                            <td>: {{$siswa->alamat_orangtua}}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Kelengkapan</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    Gambar Ijazah : <br>
                    @if($siswa->img_ijazah=="-")
                    Belum Upload Gambar
                    @else
                    <img src="{{url('itlabil/image/image_user')}}/{{$siswa->img_ijazah}}" alt="{{$siswa->img_ijazah}}" class="img-thumbnail" width="600px"><br><br>
                    {!! Form::model($siswa, ['route' => ['admin.persyaratan.update', $siswa],'method' =>'patch','class'=>'form-horizontal','files'=>true])!!}
                    @include('form.ubah._admin_ijazah', ['model' => $siswa])
                    {!! Form::close() !!}
                    @endif
                    <br><br><br>
                    Gambar SKHU : <br>
                    @if($siswa->img_skhu=="-")
                    Belum Upload Gambar
                    @else
                    <img src="{{url('itlabil/image/image_user')}}/{{$siswa->img_skhu}}" alt="{{$siswa->img_skhu}}" class="img-thumbnail" width="600px"><br><br>
                    {!! Form::model($siswa, ['route' => ['admin.persyaratan.update', $siswa],'method' =>'patch','class'=>'form-horizontal','files'=>true])!!}
                    @include('form.ubah._admin_skhu', ['model' => $siswa])
                    {!! Form::close() !!}
                    @endif
                </div>
            </div>
        </div>
    </div>
    <a href="{{ route('admin.siswa.index') }}" class="btn btn-primary">Kembali</a> <a href="{{ route('admin.siswa.edit', $siswa->id) }}" class="btn btn-success">Ubah</a>
</section>
@endsection

resources/views/admin/siswa/siswa.blade.php
@extends('layouts.admin')

@section('content')

<section class="content-header">
    <h1>
        Data Siswa Baru
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">

            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Data Siswa Baru</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>ID Daftar</th>
                                <th>JK</th>
                                <th>NISN</th>
                                <th>Asal Sekolah</th>
                                <th>Jurusan 1</th>
                                <th>Jurusan 2</th>
                                <th>Telp</th>
                                <th>Administrasi</th>
                                <th>Tgl Daftar</th>
                                <th>Tipe Daftar</th>
                                <th>Keterangan</th>
                                <th>Tahun Ajaran</th>
                                <th>Detail</th>
                                <th>Ubah</th>
                                <th>Hapus</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($siswa as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->nama }}</td>
                                <td>{{ $item->id_daftar }}</td>
                                <td>{{ $item->jk }}</td>
                                <td>{{ $item->nisn }}</td>
                                <td>{{ $item->asal_sekolah }}</td>
                                <td>{{ $item->jurusan_1 }}</td>
                                <td>{{ $item->jurusan_2 }}</td>
                                <td>{{ $item->telp }}</td>
                                @if($item->status_bayar=="Lunas")
                                <td><span class="badge bg-green">{{ $item->status_bayar }}</span></td>
                                @else
                                <td><span class="badge bg-red">{{ $item->status_bayar }}</span></td>
                                @endif
                                <td>{{ $item->created_at->format('d/m/Y') }}</td>
                                <td>{{ $item->daftar }}</td>
                                <td>{{ $item->ket }}</td>
                                <td>{{ $item->tahun_ajaran }}</td>
                                <td><a href="{{ route('admin.siswa.show', $item->id) }}" class="btn btn-success">Lihat</a></td>
                                <td><a href="{{ route('admin.siswa.edit', $item->id) }}" class="btn btn-primary">Ubah</a></td>
                                <td>
                                    {{ Form::open(['route' => ['admin.siswa.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                    {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                    {{ Form::close() }}
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/siswa/tambah_siswa.blade.php
@extends('layouts.admin')

@section('content')

    <section class="content-header">
        <h1>
            Tambah Data Siswa Baru
        </h1>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                {!! Form::open(['route' => 'admin.siswa.store', 'class'=>'form-horizontal','files'=>true])!!}
                    @include('form.tambah._admin_siswa')
                {!! Form::close() !!}

            </div>
        </div>
    </section>
@endsection